export const ROUTES = {
  HOME: '/',
  SERVICES: '/services',
  SERVICE_DETAIL: (slug: string) => `/services/${slug}`,
  TRAINERS: '/trainers',
  TRAINER_PROFILE: (id: string) => `/trainers/${id}`,
  PROGRAMS: '/programs',
  PROGRAM_DETAIL: (slug: string) => `/programs/${slug}`,
  DIET_PLANS: '/diet-plans',
  DIET_PLAN_DETAIL: (slug: string) => `/diet-plans/${slug}`,
  BLOG: '/blog',
  BLOG_POST: (slug: string) => `/blog/${slug}`,
  ABOUT: '/about',
  CONTACT: '/contact',
  PRICING: '/pricing',
  BOOKING: (slug: string) => `/book/${slug}`,
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  ACCOUNT: '/account',
  ACCOUNT_BOOKINGS: '/account/bookings',
  ACCOUNT_PROFILE: '/account/profile',
  ACCOUNT_SETTINGS: '/account/settings',
  SHOWCASE: '/showcase',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  NOT_FOUND: '/404',
} as const
